# Python review

Goals: 
- recall basic Python vocabulary
- practice markdown

## Libraries and packages

**library**: a collection of code that we can use to perform specific tasks in our programs. 

**NumPy**:
- core library for numerical computing in Python
- many other libraries use NumPy arrrays as building blocks
- computations on NumPy are optomized for speed and memory usage

Let's import NumPy with **standard abbreviation**

In [1]:
import numpy as np

## Variables 

**variable**: a name we assign to a particular object in Python

Example:

In [2]:
# Assign to small array to a variable a 
a = np.array([[1,1,2],[3,5,8]])

In [3]:
# Run cell with the variable name to show the value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
# Use 'print' function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Objects
**object** (informally speaking) is a bundle of *properties* and *actions* about something specific.

Example: 

Object: data frame

Poperties: number rows, names of the columns, date created

Actions: selecting a specific row, adding a new column

A varialbe is the name we give a specific object, and the same object can be referenced by different variables. 

In practice, we can often use variable and object interchangeably.

## Types 

Every object in Python has a **type**. The type tells us what kind of object it is.

We can also call the type of an object, the **class** of an object and they both mean what kind of object we have. 

In [6]:
print(a)

# Check the type/class of a variable/object by using 'type' function
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

In [8]:
print(a[0,0])

# Check the type of an entry on the array by indexing
type(a[0,0])

1


numpy.int64

Notice that `type(a[0])` is `numpy.int64` and not just the standard Python integer type. This is telling us that 1 is an integer stored as a 64-bit number.

In [10]:
print(a[1,1])

5


## Functions

`print` was our first example of a Python **function**.

Functions take in a set of **arguments** and those arguments creat an **output**.

argument = parameter.

We can ask information about a functions execution `?function`

In [11]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

This information is a **docstring**.

A function has two types of arguments:

- **non-optional argument**: arguments *you* need to specifiy for the function to do something

- **optional arguments**: arguments that are pre-filled with a default value by the function. You can override them. Optional arguments appear inside the parenthesis in the form `optional_argument=default_value`

In [12]:
print('changing the default end argument', end = ':)')

changing the default end argument:)

## Attributes & methods

An object in Python has attributes and methods.

- **attribute**: a property of the object, some piece of information about it

- **method**: a procedure associated with the object, an action where the main ingedient is the object. 

### Check-in

Fish:

- length, color, species
- die(), bite(), swim()

**Example**
Attributes for `numpy.arrays`

We can access a variables attributes and methods by adding a pertiod `.` at the end of the variable's name. 

`variable.method()` or `variable.attribute`

In [13]:
a.shape

(2, 3)

In [14]:
type(a.shape)

tuple

In [16]:
# Methods examples
# min() returns the minimum value along the specified axis
a.min(axis=0)

array([1, 1, 2])

## Check-in 

We can also call the `min` method without any parameters:

In [17]:
a.min()

1

Remember: methods are functions associated with an object.

In [18]:
type(a.min)

builtin_function_or_method

 ## Excercise
 
 1. Read the `print` function help. What is the type of argument `sep`? Is this an optional or non-optional argument? why?
 
 2. Creat two new variables, one with the integer value 77 and another one with the string 99.
 
 3.  Use your variables to print `77%99%77` by changing the value of the optional arguments in `print`.

In [20]:
?print
# `sep` is an optional argument because it defaults to a space if not specified

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [22]:
n1 = 77 
n2 = '99'

In [28]:
print(n1, n2, n1, sep= '%')

77%99%77
